- name: "Create filestore-server deploy yaml file"
  template:
    src: deploy.yml.j2
    dest: /tmp/deploy.yaml

- name: "Create filestore-server resources"
  shell: "oc new-app -f /tmp/deploy.yaml -n {{ namespace }}"
  
- name: "Retrieve route to filestore-server"
  shell: "oc get routes filestore-server -n {{ namespace }} | grep -v NAME | awk '{print $2}'"
  register: fhsync_route

- name: "Create filestore-server secret yaml file"
  template:
    src: secret.yml.j2
    dest: /tmp/secret.yaml

- name: "Create FH Sync-server secret"
  shell: "oc create -f /tmp/secret.yaml -n {{ namespace }}"
